apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.cm.yaml
  - api.secret.yaml
  - roles.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: image-metadata-collector
