apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-scan-collector
  namespace: cluster-image-scanner-image-collector
spec:
  template:
    spec:
      activeDeadlineSeconds: 3600
      serviceAccountName: image-collector
      automountServiceAccountToken: true # mount cluster-scan
      restartPolicy: Never
      containers:
        - name: cluster-scan-image-collector
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1001
          image: "quay.io/sdase/sdase-image-collector:a8587e6d3c19445399df79681fc0af691174540a" # TODO Version Automation
          command: [ "/app" ]
          args: [
            "--cluster-name", "lord-of-the-rings",
            "--scan-interval", "5",
            "--storage", "s3",
            "--s3-endpoint", "minio-hl:9000",
            "--s3-bucket", "local",
            "--s3-insecure", "true",
            "--s3-region", "eu-west-1",
          ]
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "testtesttest"
            - name: AWS_SECRET_ACCESS_KEY
              value: "testtesttest"
          resources:
            limits:
              #cpu: 400m no limit during test
              memory: 124Mi
