name: Testing
on:
  - pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.0
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
      - name: image collector test integration
        run: |
          cd test_actions/imagecollector
          ./setup.bash
